### ISSUE TITLE
[BUG] DNS Records are not being updated using the DigitalOcean provider

### ISSUE THREAD

**Issue by OrKarstoft** [OrKarstoft/dns-updater#16]
**Describe the Bug**
When my WAN IP changes, the application does not update the records accordingly.

**To Reproduce**
 
1. Configuration used
```yaml
provider:
  name: digitalocean
  config:
    token: <DO_TOKEN>

tracing:
  enabled: true
  host: localhost
  port: 4317
  allowInsecure: true

updates:
  - domain: <DOMAIN>
    zone: <ZONE>
    type: A
    records:
    - record1
    - record2

```
2. Action performed

Running the application when the WAN IP has changed.

3. Error received

None.
 
**Expected Behavior**
```
2025/02/18 18:15:52 General error: Record record1 not found in domain <DOMAIN>
2025/02/18 18:15:52 General error: Record record2 not found in domain <DOMAIN>
```

**Logs**
See above.

**Environment:**
 - OS: MacOS Sequoia 15.3
 - DNS Provider: DigitalOcean
 - Version: Pulled from main branch ([9f81e51](https://github.com/OrKarstoft/dns-updater/tree/9f81e51aab5466e48d798bdea523697101019cf0))

**Additional Context**
I believe the issue is [here](https://github.com/OrKarstoft/dns-updater/blob/9f81e51aab5466e48d798bdea523697101019cf0/dns/providers/digitalocean/digitalocean.go#L68). It compares the DNS record IP with the new IP; if they are not equal, it will not continue.

I also checked the GCP provider, which does not have the same issue.
